CREATE TYPE "role_enum" AS ENUM (
  'EMPLOYEE',
  'MANAGER',
  'ADMIN'
);

CREATE TYPE "leave_type_enum" AS ENUM (
  'ANNUAL_LEAVE',
  'EXCUSE_LEAVE',
  'SICK_LEAVE'
);

CREATE TYPE "approval_status_enum" AS ENUM (
  'PENDING',
  'APPROVED',
  'REJECTED'
);

CREATE TYPE "equipment_status_enum" AS ENUM (
  'IN_STORAGE',
  'ASSIGNED',
  'RETURNED'
);

CREATE TYPE "equipment_type_enum" AS ENUM (
  'MONITOR',
  'KEYBOARD',
  'MOUSE',
  'LAPTOP',
  'EARPHONES',
  'MICROPHONE'
);

CREATE TABLE "employee" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "surname" varchar(50) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password" varchar(100) NOT NULL,
  "registration_number" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "date_of_birth" date NOT NULL,
  "department_id" integer NOT NULL,
  "remaining_leave_days" integer NOT NULL DEFAULT 0,
  "role" role_enum DEFAULT 'EMPLOYEE',
  "profile_photo" varchar(255),
  "is_active" boolean DEFAULT true
);

CREATE TABLE "department" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "skill" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "employee_skill" (
  "employee_id" integer,
  "skill_id" integer,
  PRIMARY KEY ("employee_id", "skill_id")
);

CREATE TABLE "leave_request" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "leave_type" leave_type_enum NOT NULL,
  "employee_id" integer,
  "request_note" varchar(400),
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "request_days" integer NOT NULL,
  "status" approval_status_enum DEFAULT 'PENDING',
  "approver_id" integer,
  "action_date" timestamp
);

CREATE TABLE "meeting_reservation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meeting_room_id" integer NOT NULL,
  "employee_id" integer NOT NULL,
  "title" varchar(100) NOT NULL,
  "reservation_date" date NOT NULL,
  "start_time" time NOT NULL,
  "end_time" time NOT NULL
);

CREATE TABLE "meeting_room" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "capacity" integer NOT NULL
);

CREATE TABLE "equipment_request" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" integer,
  "equipment_id" integer,
  "status" approval_status_enum DEFAULT 'PENDING',
  "approver_id" integer,
  "action_date" timestamp
);

CREATE TABLE "equipments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "equipment_type" equipment_type_enum,
  "brand" varchar(100),
  "model" varchar(100),
  "serial_number" varchar(100) UNIQUE NOT NULL,
  "status" equipment_status_enum DEFAULT 'IN_STORAGE'
);

CREATE TABLE "equipment_assignments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" integer,
  "equipment_id" integer,
  "delivery_date" date NOT NULL,
  "return_date" date
);

CREATE TABLE "announcements" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(400) NOT NULL,
  "content" varchar(2000) NOT NULL,
  "author_id" integer,
  "created_at" timestamp
);

CREATE TABLE "comments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "announcement_id" integer,
  "author_id" integer,
  "content" varchar(2000) NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "likes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "announcement_id" integer,
  "liker_id" integer
);

CREATE TABLE "appreciations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" integer NOT NULL,
  "receiver_id" integer NOT NULL,
  "content" varchar(2000) NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ON "likes" ("announcement_id", "liker_id");

ALTER TABLE "employee" ADD FOREIGN KEY ("department_id") REFERENCES "department" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employee_skill" ADD FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employee_skill" ADD FOREIGN KEY ("skill_id") REFERENCES "skill" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "leave_request" ADD FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "leave_request" ADD FOREIGN KEY ("approver_id") REFERENCES "employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meeting_reservation" ADD FOREIGN KEY ("meeting_room_id") REFERENCES "meeting_room" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meeting_reservation" ADD FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipment_request" ADD FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipment_request" ADD FOREIGN KEY ("equipment_id") REFERENCES "equipments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipment_request" ADD FOREIGN KEY ("approver_id") REFERENCES "employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipment_assignments" ADD FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipment_assignments" ADD FOREIGN KEY ("equipment_id") REFERENCES "equipments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "announcements" ADD FOREIGN KEY ("author_id") REFERENCES "employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("announcement_id") REFERENCES "announcements" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("author_id") REFERENCES "employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "likes" ADD FOREIGN KEY ("announcement_id") REFERENCES "announcements" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "likes" ADD FOREIGN KEY ("liker_id") REFERENCES "employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "appreciations" ADD FOREIGN KEY ("sender_id") REFERENCES "employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "appreciations" ADD FOREIGN KEY ("receiver_id") REFERENCES "employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;
